name: New Issue Approval From Ice Box

on:
  issues:
    types: [edited]
    filters:
      project_column:
        project: "Project Board"
        column: "Ice Box"

jobs:
  Log-Trigger:
    runs-on: ubuntu-latest
    steps:
     - run: echo "🎉 The job was triggered"


  Check_Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check dependencies
        id: check
        uses: actions/github-script@v3
        with:
          script: |
            const issues = ${{ github.event.issue.body }}
            console.log("The issue body is:", issues);

