name: New Issue Approval From Ice Box

on:
  issue_comment:
    types: [edited]
    filters:
      project_column:
        project: "Project Board"
        column: "Ice Box"


jobs:
  Check_Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check dependencies
        id: check
        uses: actions/github-script@v3
        with:
          script: |
            const issues = issue.comment.body.split('\n').map(d => d.trim());
            const checkedDependencies = issues.filter(d => d.endsWith(':checked'));
            const linkedIssues = checkedDependencies.filter(d => d.includes(':issue:'));
            //possibly change to issues.filter for above

            if (linkedIssues.length !== checkedDependencies.length) {
              console.log('Not all dependencies have issues linked to them');
              exit(1);
            }
            else {
              console.log('They\'re all check marked! Next step is to move onto icebox');
              echo "::check-output name=run_next_job::yes"
            }
    outputs:
      run_next_job: ${{steps.check.outputs.run_next_job}}

  Move_To_New_Issue_Approval_Column:
    needs: Check_Dependencies
    if: needs.Check_Dependencies.outputs.run_next_job == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Move To New Issue Approval Column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Project Board
          column: "New Issue Approval"
          repo-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}

  Add_Ready_For_Dev_Lead_Label:
      needs: Check_Dependencies
      if: needs.Check_Dependencies.outputs.run_next_job == 'yes'
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
        - uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["ready for dev lead"]
              })
